nodeLinker: node-modules

npmScopes:
  zk-email:
    npmRegistryServer: "https://registry.npmjs.org"
    npmAlwaysAuth: false

packageExtensions:
  circomlib@*:
    dependencies:
      circomlibjs: "*" 