[profile.default]
src = "src"
out = "out"
libs = ["lib", "node_modules"]
solc_version = "0.8.19"
optimizer = true
optimizer_runs = 200

[profile.deps]
forge-std = { git = "https://github.com/foundry-rs/forge-std" }

[rpc_endpoints]
sepolia = "https://eth-sepolia.g.alchemy.com/v2/1Gf850C8kHj149mN6ux_ZzBhfuab_Jlx"

[etherscan]
sepolia = { key = "I666RW9DX43RDY3W277ZDC2CMNB6IGXNFC" }

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
